name: PHP Tests

on:
  push: 
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: oop_project
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_mysql

      - name: Install dependencies
        run: composer install

      - name: Wait for MySQL ready
        run: |
          sleep 20
          mysql -h 127.0.0.1 -uroot -proot -e "SHOW DATABASES;"

      - name: Run PHPUnit tests
        run: chmod +x vendor/bin/phpunit && vendor/bin/phpunit --colors=always
